#!/usr/bin/env bash
# Install nginx to return 'Hello World!' on a GET request

sudo apt update -y
sudo apt install -y nginx
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start