#!/usr/bin/env bash
# Installs Nginx and make configurations configurations:

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install -y nginx

# Creating an index.html page
mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

# Creating a 404 Custom error page
touch /var/www/html/custom404.html
echo "Ceci n'est pas une page" > /var/www/html/custom404.html

server="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://youtube.com/;
    }

    error_page 404 /custom404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}"

# Creating an HTTP response header
sudo echo > /etc/nginx/sites-available/default

# Restart nginx after implementing changes
sudo service nginx restart
