#!/usr/bin/env bash
# fix nginx listening | port 80

# Create symbolic link to deafult file in sites-available
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Nginx Restart
sudo service nginx start
