#!/usr/bin/env bash
# configure server to listening on port 80 of all server's active IPv4

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart

echo "" | sudo dd status=none of=/run/nginx.pid
