#!/usr/bin/env bash
# configure server to listening on port 80 of all server's active IPv4

sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
# service restart
sudo  service nginx restart
# pkill
pkill  --oldest nginx
