#!/usr/bin/env bash
# Parses Apache log files [list format].
# Groups visitors by IP & HTTP status code.
# Displays number of occurrences, IP, & HTTP status
# Code of each log, in sorted order.

awk '{print $1,$9}' apache-access.log | sort | uniq -c | sort -r
