#!/usr/bin/env bash
# Configures Ubuntu server as follows:
# localhost to resolve to 127.0.0.2
# facebook to resolve to 8.8.8.8

cp /etc/hosts ~/new_hosts
echo "127.0.0.2     localhost" > ~/new_hosts
echo "8.8.8.8       facebook.com" >> ~/new_hosts

cat ~/new_hosts > /etc/hosts
