#!/usr/bin/env bash
# Fixes web server to run Nginx as nginx user listening on port 8080.

# set user in config by replacing '#user' and it's value
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# replace port 80 with 8080 in sites-available config
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# give owner read and write permissions to config file
chmod 644 /etc/nginx/nginx.conf

#  kill apache process if it is running
pkill apache2

# now start nginx service with new nginx user
sudo -u nginx service nginx start
